# Generated by Django 3.1.4 on 2020-12-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-datefinish'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
    ]
