# Generated by Django 3.1.4 on 2020-12-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20201210_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
