# Generated by Django 3.1.4 on 2020-12-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
