# Generated by Django 3.1.4 on 2020-12-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
