# Generated by Django 3.1.4 on 2020-12-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201210_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
