# Generated by Django 3.1.4 on 2020-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='work', verbose_name='Imagen'),
        ),
    ]
