# Generated by Django 3.1.4 on 2020-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20201212_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa Cliente'),
        ),
        migrations.AddField(
            model_name='work',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='work', verbose_name='Imagen Cliente'),
        ),
    ]
