# Generated by Django 3.1.4 on 2020-12-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20201212_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='work',
            name='client_image',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa Cliente')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='work', verbose_name='Imagen Cliente')),
                ('datestart', models.DateField(verbose_name='Fecha de comienzo')),
                ('datefinish', models.DateField(verbose_name='Fecha de finalización')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.work', verbose_name='Empresa Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-datefinish'],
            },
        ),
    ]
